import React, { useEffect, useMemo, useState } from 'react';
import { Bell, Building2, Edit3, Plus, Search, Trash2 } from 'lucide-react';
import { collection, deleteDoc, doc, onSnapshot, setDoc } from 'firebase/firestore';
import { db } from '../firebase';
import { firebaseErrorMessage } from '../utils/firebaseError';

const emptyForm={nome:'',razaoSocial:'',cnpj:'',responsavel:'',telefone:'',whatsapp:'',email:'',cidade:'',uf:'MT',status:'ativo',observacoes:''};
const id=()=>`cli_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;

export default function ClientesPage({canEdit=false,canDelete=false,userEmail=''}){
  const [rows,setRows]=useState([]),[query,setQuery]=useState(''),[form,setForm]=useState(emptyForm),[editing,setEditing]=useState(null),[open,setOpen]=useState(false),[toast,setToast]=useState(''),[loading,setLoading]=useState(true);
  useEffect(()=>onSnapshot(collection(db,'clientes'),snap=>{setRows(snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.nome||'').localeCompare(b.nome||'')));setLoading(false)},err=>{setToast(firebaseErrorMessage(err,'carregar clientes'));setLoading(false)}),[]);
  const filtered=useMemo(()=>rows.filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase())),[rows,query]);
  function newItem(){setForm(emptyForm);setEditing(null);setOpen(true)}
  function editItem(row){setForm({...emptyForm,...row});setEditing(row.id);setOpen(true)}
  async function save(e){e.preventDefault();if(!form.nome.trim())return setToast('Informe o nome do cliente.');const now=new Date().toISOString();const record={...form,updatedAt:now,updatedBy:userEmail};if(!editing){record.createdAt=now;record.createdBy=userEmail;}try{await setDoc(doc(db,'clientes',editing||id()),record,{merge:true});setOpen(false);setEditing(null);setForm(emptyForm);setToast('Cliente salvo com sucesso.')}catch(err){setToast(firebaseErrorMessage(err,'salvar cliente'))}}
  async function remove(row){if(!confirm(`Excluir o cliente ${row.nome}?`))return;try{await deleteDoc(doc(db,'clientes',row.id));setToast('Cliente excluído.')}catch(err){setToast(firebaseErrorMessage(err,'excluir cliente'))}}
  return <div className="report-wrap"><section className="master-toolbar"><div className="search"><Search size={18}/><input placeholder="Buscar nome, CNPJ, responsável, cidade..." value={query} onChange={e=>setQuery(e.target.value)}/></div>{canEdit&&<button className="primary" onClick={newItem}><Plus size={18}/> Novo cliente</button>}</section><section className="report-table-card"><div className="report-title"><div><h2>Cadastro mestre de clientes</h2><p>Base única para vincular veículos, equipamentos e demandas.</p></div><strong>{filtered.length} cliente(s)</strong></div>{loading?<div className="empty">Carregando...</div>:<div className="table-scroll"><table className="report-table"><thead><tr><th>Cliente</th><th>CNPJ</th><th>Responsável</th><th>Contato</th><th>Cidade/UF</th><th>Status</th><th>Ações</th></tr></thead><tbody>{filtered.map(row=><tr key={row.id}><td><strong>{row.nome}</strong><small>{row.razaoSocial||'-'}</small></td><td>{row.cnpj||'-'}</td><td>{row.responsavel||'-'}</td><td>{row.whatsapp||row.telefone||'-'}<small>{row.email||''}</small></td><td>{[row.cidade,row.uf].filter(Boolean).join('/')||'-'}</td><td><span className={`report-status ${row.status==='ativo'?'done':'late'}`}>{row.status==='ativo'?'Ativo':'Inativo'}</span></td><td><div className="actions">{canEdit&&<button onClick={()=>editItem(row)} title="Editar"><Edit3 size={16}/></button>}{canDelete&&<button onClick={()=>remove(row)} title="Excluir"><Trash2 size={16}/></button>}</div></td></tr>)}{!filtered.length&&<tr><td colSpan="7" className="no-results">Nenhum cliente encontrado.</td></tr>}</tbody></table></div>}</section>{open&&<div className="modal-backdrop"><div className="modal modal-large"><div className="modal-title"><div><h2>{editing?'Editar cliente':'Novo cliente'}</h2><p>Os dados ficam sincronizados pelo Firestore.</p></div><button onClick={()=>setOpen(false)}>×</button></div><form onSubmit={save}>{[['nome','Nome / Nome fantasia'],['razaoSocial','Razão social'],['cnpj','CNPJ'],['responsavel','Responsável'],['telefone','Telefone'],['whatsapp','WhatsApp'],['email','E-mail'],['cidade','Cidade'],['uf','UF']].map(([k,l])=><div className="field" key={k}><label>{l}</label><input value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/></div>)}<div className="field"><label>Status</label><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="ativo">Ativo</option><option value="inativo">Inativo</option></select></div><div className="field full"><label>Observações</label><textarea rows="4" value={form.observacoes||''} onChange={e=>setForm({...form,observacoes:e.target.value})}/></div><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary">Salvar cliente</button></div></form></div></div>}{toast&&<div className="toast"><Bell size={18}/>{toast}</div>}</div>;
}
