import React, { useEffect, useMemo, useState } from 'react';
import { Bell, Car, Edit3, Plus, Search, Trash2 } from 'lucide-react';
import { collection, deleteDoc, doc, onSnapshot, setDoc } from 'firebase/firestore';
import { db } from '../firebase';
import { firebaseErrorMessage } from '../utils/firebaseError';
const emptyForm={clienteId:'',clienteNome:'',placa:'',frota:'',marca:'',modelo:'',ano:'',cor:'',chassi:'',renavam:'',status:'ativo',observacoes:''};
const id=()=>`vei_${Date.now()}_${Math.random().toString(36).slice(2,8)}`;
export default function VeiculosPage({canEdit=false,canDelete=false,userEmail=''}){
 const [rows,setRows]=useState([]),[clientes,setClientes]=useState([]),[query,setQuery]=useState(''),[form,setForm]=useState(emptyForm),[editing,setEditing]=useState(null),[open,setOpen]=useState(false),[toast,setToast]=useState('');
 useEffect(()=>onSnapshot(collection(db,'veiculos'),s=>setRows(s.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>(a.placa||'').localeCompare(b.placa||''))),err=>setToast(firebaseErrorMessage(err,'carregar veículos'))),[]);
 useEffect(()=>onSnapshot(collection(db,'clientes'),s=>setClientes(s.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.status!=='inativo').sort((a,b)=>(a.nome||'').localeCompare(b.nome||'')))),[]);
 const filtered=useMemo(()=>rows.filter(r=>JSON.stringify(r).toLowerCase().includes(query.toLowerCase())),[rows,query]);
 function newItem(){setForm(emptyForm);setEditing(null);setOpen(true)} function editItem(r){setForm({...emptyForm,...r});setEditing(r.id);setOpen(true)}
 async function save(e){e.preventDefault();if(!form.placa.trim())return setToast('Informe a placa.');const cliente=clientes.find(c=>c.id===form.clienteId);const now=new Date().toISOString();const rec={...form,placa:form.placa.toUpperCase(),clienteNome:cliente?.nome||form.clienteNome||'',updatedAt:now,updatedBy:userEmail};if(!editing){rec.createdAt=now;rec.createdBy=userEmail;}try{await setDoc(doc(db,'veiculos',editing||id()),rec,{merge:true});setOpen(false);setToast('Veículo salvo com sucesso.')}catch(err){setToast(firebaseErrorMessage(err,'salvar veículo'))}}
 async function remove(r){if(!confirm(`Excluir o veículo ${r.placa}?`))return;try{await deleteDoc(doc(db,'veiculos',r.id));setToast('Veículo excluído.')}catch(err){setToast(firebaseErrorMessage(err,'excluir veículo'))}}
 return <div className="report-wrap"><section className="master-toolbar"><div className="search"><Search size={18}/><input placeholder="Buscar placa, cliente, marca, modelo..." value={query} onChange={e=>setQuery(e.target.value)}/></div>{canEdit&&<button className="primary" onClick={newItem}><Plus size={18}/> Novo veículo</button>}</section><section className="report-table-card"><div className="report-title"><div><h2>Veículos</h2><p>Frota vinculada ao cadastro mestre de clientes.</p></div><strong>{filtered.length} veículo(s)</strong></div><div className="table-scroll"><table className="report-table"><thead><tr><th>Placa</th><th>Cliente</th><th>Frota</th><th>Marca / Modelo</th><th>Ano</th><th>Status</th><th>Ações</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id}><td><strong>{r.placa}</strong></td><td>{r.clienteNome||'-'}</td><td>{r.frota||'-'}</td><td>{r.marca||'-'}<small>{r.modelo||''}</small></td><td>{r.ano||'-'}</td><td><span className={`report-status ${r.status==='ativo'?'done':'late'}`}>{r.status==='ativo'?'Ativo':'Inativo'}</span></td><td><div className="actions">{canEdit&&<button onClick={()=>editItem(r)}><Edit3 size={16}/></button>}{canDelete&&<button onClick={()=>remove(r)}><Trash2 size={16}/></button>}</div></td></tr>)}{!filtered.length&&<tr><td colSpan="7" className="no-results">Nenhum veículo encontrado.</td></tr>}</tbody></table></div></section>{open&&<div className="modal-backdrop"><div className="modal modal-large"><div className="modal-title"><div><h2>{editing?'Editar veículo':'Novo veículo'}</h2><p>Cadastre o veículo e vincule ao cliente.</p></div><button onClick={()=>setOpen(false)}>×</button></div><form onSubmit={save}><div className="field full"><label>Cliente</label><select value={form.clienteId} onChange={e=>setForm({...form,clienteId:e.target.value})}><option value="">Selecione...</option>{clientes.map(c=><option key={c.id} value={c.id}>{c.nome}</option>)}</select></div>{[['placa','Placa'],['frota','Frota'],['marca','Marca'],['modelo','Modelo'],['ano','Ano'],['cor','Cor'],['chassi','Chassi'],['renavam','Renavam']].map(([k,l])=><div className="field" key={k}><label>{l}</label><input value={form[k]||''} onChange={e=>setForm({...form,[k]:e.target.value})}/></div>)}<div className="field"><label>Status</label><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="ativo">Ativo</option><option value="inativo">Inativo</option></select></div><div className="field full"><label>Observações</label><textarea rows="3" value={form.observacoes||''} onChange={e=>setForm({...form,observacoes:e.target.value})}/></div><div className="modal-actions"><button type="button" className="secondary" onClick={()=>setOpen(false)}>Cancelar</button><button className="primary">Salvar veículo</button></div></form></div></div>}{toast&&<div className="toast"><Bell size={18}/>{toast}</div>}</div>;
}
